### ISSUE TITLE
Lag spikes on reset

### ISSUE THREAD

**Issue by confuser** [MC-Minigames/MGSkyWars#2]
Once a game has completed, the server TPS reduces causing a lag spike

http://timings.aikar.co/?url=9706342

**Comment by confuser** [comment]
2 PRs sent to the API repo that solves this issue

**Comment by instance01** [comment]
Sorry for not answering, I'm back now! I'll take a look at everything in a sec, thank you.

**Comment by instance01** [comment]
Closing as your reset commit fixes it (https://github.com/instance01/MinigamesAPI/commit/4d38a08b7f6c39ed328931d036d9936fce8f0ed7) and the scoreboard will be re-coded to use version-specific functions.
