### ISSUE TITLE
Chest items have to have a % and quantity

### ISSUE THREAD

**Issue by confuser** [MC-Minigames/MGSkyWars#4]
An exception gets thrown otherwise on https://github.com/MC-Minigames/MGSkyWars/blob/master/src/com/comze_instancelabs/mgskywars/Main.java#L372

2015-01-09 13:45:32 [INFO] Failed to load class items: 1 at [1] 95 [0] 372

E.g.

```
265;257*1;3;272
```

throws an error, but the following does not

```
265*3%100;257*1%100;3*16%100;272*1%100
```

**Comment by instance01** [comment]
I'll take a look at this, thanks.
