### ISSUE TITLE
Permission classes should only show if they can be used

### ISSUE THREAD

**Issue by confuser** [MC-Minigames/MGSkyWars#5]
At the moment, whether or not the player has permission to use such a class, it's still displayed.

As permission classes can't be bought directly via the GUI like money ones can, it would be better to only show classes they have the perms to use.

**Comment by instance01** [comment]
That's a nice idea that could be added to the API, thanks.

**Comment by instance01** [comment]
There we go ;) https://github.com/instance01/MinigamesAPI/commit/b0ae033de6b1ba91867c05a54ce3d21ae0cceed9

**Comment by confuser** [comment]
:+1:
